esphome:
  platformio_options:
      build_flags: 
        - -DDSMR_GAS_MBUS_ID=
  name: p1-test

esp8266:
  board: d1_mini

wifi:
  ssid: 
  password: 
  fast_connect: true
  
  # Optional manual IP
  manual_ip:
     static_ip: 
     gateway: 
     subnet: 

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: 
    password: 

web_server:
  port: 80
  version: 2
  auth:
    username: 
    password: 

captive_portal:

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  password: ""

# Tutorial: https://community.home-assistant.io/t/p1-monitor-or-dsmr-slimme-meter-integration/352903/2
uart:
  rx_pin: D7
  baud_rate: 9600
  data_bits: 7
  parity: EVEN
  stop_bits: 1
  #rx_buffer_size: 1700
  #rx_buffer_size: 1500

dsmr:
  #gas_mbus_id: 4730303135353631303131353439363133
  crc_check: false
  request_pin: D5
  request_interval: 5s
  #max_telegram_length: 1700

sensor:
  - platform: dsmr
    energy_delivered_lux:
      name: "dsmr_energy_delivered_tarifflux"
    energy_delivered_tariff1:
      name: "Energy Consumed Tariff 1"
    energy_delivered_tariff2:
      name: "Energy Consumed Tariff 2"
    energy_returned_tariff1:
      name: "Energy Produced Tariff 1"
    energy_returned_tariff2:
      name: "Energy Produced Tariff 2"
    power_delivered:
      name: "Power Consumed"
      accuracy_decimals: 3
    power_returned:
      name: "Power Produced"
      accuracy_decimals: 3
    electricity_failures:
      name: "Electricity Failures"
      icon: mdi:alert
    electricity_long_failures:
      name: "Long Electricity Failures"
      icon: mdi:alert
    voltage_l1:
      name: "Voltage Phase 1"
    voltage_l2:
      name: "Voltage Phase 2"
    voltage_l3:
      name: "Voltage Phase 3"
    current_l1:
      name: "Current Phase 1"
    current_l2:
      name: "Current Phase 2"
    current_l3:
      name: "Current Phase 3"
    power_delivered_l1:
      name: "Power Consumed Phase 1"
      accuracy_decimals: 3
    power_delivered_l2:
      name: "Power Consumed Phase 2"
      accuracy_decimals: 3
    power_delivered_l3:
      name: "Power Consumed Phase 3"
      accuracy_decimals: 3
    power_returned_l1:
      name: "Power Produced Phase 1"
      accuracy_decimals: 3
    power_returned_l2:
      name: "Power Produced Phase 2"
      accuracy_decimals: 3
    power_returned_l3:
      name: "Power Produced Phase 3"
      accuracy_decimals: 3
    gas_delivered:
      name: "Gas Consumed"

text_sensor:
  - platform: dsmr
    identification:
      name: "DSMR Identification"
    p1_version:
      name: "DSMR Version"
    # timestamp:
    #   name: "DSMR Timestamp"
    # electricity_tariff:
    #   name: "‘0001’= normal - ‘0002’=low tariff"
    # electricity_failure_log:
    #   name: "Electricity Failure Log"
    gas_delivered_text:
      name: "gas delivered raw"
    gas_equipment_id:
      name: "gas_mbus ID"
    # message_short:
    #   name: "message Short"
    # message_long:
    #   name: "message Long"